appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: k+iYtaOBQeqc3ka7ubvwBU3CwIP7qhlNhDIyS+X7HM9rHj6X2AQtEXd1cSp7wISXY3NeK95+9AV+FLWcNTropNePqKyRCYZerzOPKgMghT6yQipw7KQvIGNm6mXS/fHwP/IwLeTX9VsDJ8YT3tf2NPUv2CVfL/gIo2PLIxNB/08THopA0bjGmeOtK/7CRRL7Y/xpo1U7Hz+rxsk+rSEjafre/WicISEuTY0wf3UFYTRaTOm9ioEsbE13N8yIxl5GA6BwCjNYKhbP4hXJ4wDxIOb9AyvfSGu01cxcbddnL05X/JV7gjcSvQObaOJIHA+OckvktW1OySI9ETEhmBcu9LTZ86Hx+o/9PzMIRN8bd/6PBRWAyoY1pF4yLKb0aiqUgZWlWG+gya07fgIpI5bS3fOxaPUmG1hO5RiECYlywkJyAYaewg5CFgpo48ei0+z0rDvyrF6zFd0Eyr+gmRZMfhbOGkbxF7kDOOuTs5DfdKOD2fBbyPJpuxlF8M8Gkbs9F6TySZePoSQ8uCgzkG6QmIobhRHXEAwgLL+34KOtycSk9Hdhh5ez5XqaBSmgkIk2k3f8HYGfZVWJIY3WvhSVVZr4WOSNNkVu3ZRJercvj9yGZN7aZIxHO/IpMf5VtgUqvzfwKv2mUgH8RV3wngUfyIgBt85eqJkstxD24SUYwX4=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
